# Generated by Django 4.1.7 on 2023-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estado", name="estado", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="etapa", name="etapa", field=models.CharField(max_length=50),
        ),
    ]
