# Generated by Django 4.1.7 on 2023-03-04 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0002_alter_estado_estado_alter_etapa_etapa"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="user",),
    ]
