# Generated by Django 4.1.7 on 2023-03-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0003_remove_cliente_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "usuario", "verbose_name_plural": "usuarios"},
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
