# Generated by Django 4.1.7 on 2023-03-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0005_alter_usuario_managers_usuario_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="usuario", options={},),
        migrations.AlterModelManagers(name="usuario", managers=[],),
        migrations.RemoveField(model_name="usuario", name="date_joined",),
        migrations.RemoveField(model_name="usuario", name="email",),
        migrations.RemoveField(model_name="usuario", name="first_name",),
        migrations.RemoveField(model_name="usuario", name="groups",),
        migrations.RemoveField(model_name="usuario", name="is_active",),
        migrations.RemoveField(model_name="usuario", name="is_staff",),
        migrations.RemoveField(model_name="usuario", name="is_superuser",),
        migrations.RemoveField(model_name="usuario", name="last_name",),
        migrations.RemoveField(model_name="usuario", name="user_permissions",),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
