# Generated by Django 4.1.7 on 2023-03-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0006_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="usuario", name="last_login",),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
