# Generated by Django 4.1.7 on 2023-03-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ArkencoApi",
            "0007_remove_usuario_last_login_alter_usuario_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=200),
        ),
    ]
