# Generated by Django 4.1.7 on 2023-03-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0009_cliente_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="cliente", name="user",),
    ]
