# Generated by Django 4.1.7 on 2023-03-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0011_remove_prospecto_cliente_id"),
    ]

    operations = [
        migrations.DeleteModel(name="Cliente",),
    ]
