# Generated by Django 4.1.7 on 2023-03-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0012_delete_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("nombre_empresa", models.CharField(max_length=200)),
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.IntegerField()),
            ],
        ),
    ]
