# Generated by Django 4.1.7 on 2023-03-04 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0014_delete_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("nombre_empresa", models.CharField(max_length=200)),
                (
                    "rut",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ArkencoApi.usuario",
                    ),
                ),
            ],
        ),
    ]
