# Generated by Django 4.1.7 on 2023-03-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0015_cliente"),
    ]

    operations = [
        migrations.DeleteModel(name="Prospecto",),
    ]
