# Generated by Django 4.1.7 on 2023-03-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ArkencoApi", "0016_delete_prospecto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField()),
                ("fecha_ingreso", models.DateField()),
                ("sexo", models.CharField(max_length=20)),
                (
                    "cliente_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ArkencoApi.cliente",
                    ),
                ),
                (
                    "estado_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ArkencoApi.estado",
                    ),
                ),
                (
                    "estapa_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ArkencoApi.etapa",
                    ),
                ),
            ],
        ),
    ]
